devices:
    pattern: /devices
    defaults: { _controller: DeviceBundle:Device:index }
    
device_create:
    path: /device/add
    defaults: { _controller: DeviceBundle:Device:create }

device_show:
    path: /device/view/{id}
    defaults: { _controller: DeviceBundle:Device:show }

device_update:
    path: /device/edit/{id}
    defaults: { _controller: DeviceBundle:Device:update }

device_delete:
    path: /device/remove/{id}
    defaults: { _controller: DeviceBundle:Device:delete }
    
