devices:
    pattern: /devices
    defaults: { _controller: DeviceBundle:Device:list }
    
device_create:
    path: /device/add
    defaults: { _controller: DeviceBundle:Device:add }

device_read:
    path: /device/{id}
    defaults: { _controller: DeviceBundle:Device:view }

device_update:
    path: /device/{id}/edit
    defaults: { _controller: DeviceBundle:Device:edit }

device_delete:
    path: /device/{id}/remove
    defaults: { _controller: DeviceBundle:Device:remove }
    
