miners:
    pattern: /miners
    defaults: { _controller: MinerBundle:Miner:list }
    
miner_create:
    path: /miner/add
    defaults: { _controller: MinerBundle:Miner:add }

miner_read:
    path: /miner/{id}
    defaults: { _controller: MinerBundle:Miner:view }

miner_update:
    path: /miner/{id}/edit
    defaults: { _controller: MinerBundle:Miner:edit }

miner_delete:
    path: /miner/{id}/remove
    defaults: { _controller: MinerBundle:Miner:remove }
    
