Digmore\TickerBundle\Entity\CurrencyPair:
    type: entity
    table: currency_pair
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
