parameters:
#    remote.example.class: Digmore\RemoteBundle\Example

services:
#    remote.example:
#        class: %remote.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
